// Read-only catalogue used when the database is unreachable (e.g. a deploy without DATABASE_URL).
// Data comes from src/data/catalog.json, generated by `npx tsx prisma/export-catalog.ts`.
import catalog from "@/data/catalog.json";

type Filters = {
  search?: string;
  category?: string;
  brand?: string;
  minPrice?: number;
  maxPrice?: number;
  inStock?: boolean;
  sort?: string;
};

type CatalogProduct = (typeof catalog.products)[number];

export const fallbackCategories = () => catalog.categories;
export const fallbackBrands = () => catalog.brands;

export function fallbackProductBySlugOrId(idOrSlug: string) {
  return catalog.products.find((p) => p.id === idOrSlug || p.slug === idOrSlug) ?? null;
}

// Mirrors the filtering and sorting in getProducts()
export function fallbackProducts(filters: Filters): CatalogProduct[] {
  let result = [...catalog.products];

  if (filters.category) {
    result = result.filter((p) => p.category?.slug === filters.category || p.category?.parent?.slug === filters.category);
  }
  if (filters.brand) result = result.filter((p) => p.brand?.slug === filters.brand);
  if (filters.search) {
    const q = filters.search.toLowerCase();
    result = result.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        (p.nameML ?? "").toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q) ||
        (p.description ?? "").toLowerCase().includes(q) ||
        (p.brand?.name ?? "").toLowerCase().includes(q)
    );
  }
  if (filters.minPrice !== undefined) result = result.filter((p) => p.price >= filters.minPrice!);
  if (filters.maxPrice !== undefined) result = result.filter((p) => p.price <= filters.maxPrice!);
  if (filters.inStock) result = result.filter((p) => p.stock > 0);

  switch (filters.sort) {
    case "price-low":
      result.sort((a, b) => a.price - b.price);
      break;
    case "price-high":
      result.sort((a, b) => b.price - a.price);
      break;
    case "popular":
      result.sort((a, b) => b.soldCount - a.soldCount);
      break;
    case "name-az":
      result.sort((a, b) => a.name.localeCompare(b.name));
      break;
  }
  return result;
}
